# dependabot.yml
#
# Dependabot updates dependencies automatically to their latest versions.
#
# Docs: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2

updates:
  # Enable automatic version updates for Github Actions
  - package-ecosystem: "github-actions"
    # Look for `.github/workflows` in the `root` directory
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "deps(gha): "
    labels:
      - "dependencies"
    # ignore all patch level updates
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
  # Enable automatic version updates for Dockerfile
  - package-ecosystem: "docker"
    directory: "/.devcontainer/debian/bookworm"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(docker): "
    labels:
      - "dependencies"
