name: "Deploy to GitHub Pages"

on:
  # You can manually run this workflow.
  workflow_dispatch:
  # This workflow will run on every push to the main branch.
  push:
    branches:
      - main
    # Restrict the workflow to run only on changes to the following paths.
    paths:
      - 'playground/**'
      - '.github/workflows/deploy-gh-pages.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate version list for PHP-WASM modules (php-versions.json)
        run: |
          ./playground/build-tools/scripts/generate-php-versions-json.sh

      - name: Set Application Version (version.json)
        run: |
          ./playground/build-tools/scripts/generate-app-version-json.sh

      - name: Test JSON files for validity
        run: |
          cd playground
          for file in version.json php-versions.json examples/examples.json; do
            if [ -f "$file" ]; then
              if ! jq empty "$file"; then
                echo "Invalid JSON in $file"
                exit 1
              fi
            fi
          done

      - name: Prepare deploy folder
        run: |
          mkdir deploy
          cp -r playground/* deploy/
          cd deploy
          rm -rf .devcontainer node_modules test-results
          rm -f .editorconfig .gitignore package.json biome.json readme.md serve.sh setup.sh
          rm -rf build-tools
          rm -f examples/_get_file.php

      - name: ✔ Initialize Git and commit
        run: |
          cd deploy
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git checkout -b gh-pages
          git add .
          git commit -m "Deploy to GitHub Pages from ${GITHUB_REPOSITORY}@${GITHUB_SHA::9}"

      - name: 🚀 Push to gh-pages branch
        run: |
          cd deploy
          git push --force origin gh-pages
